export { MainLayout } from './layouts/main-layout/index.tsx'

export { HeadingWithList } from '@/components/shared/heading-with-list/index.tsx'
export { SideLink, type ISideLinkProps } from './shared/side-link/index.tsx'
export { Heading, type IHeadingProps } from './shared/heading/index.tsx'
export { ColorBox, type IColorBoxProps } from './shared/color-box/index.tsx'
export { Sidebar } from './shared/sidebar/index.tsx'
export { TagBtn, type ITagBtnProps } from './shared/tag-btn/index.tsx'
export { Button, type ButtonType } from './shared/button/index.tsx'
export { DateCounter, type IDateCounterProps } from './shared/date-counter/index.tsx'
